"""Changed quote

Revision ID: 114df3b64e8
Revises: 47df965c128
Create Date: 2015-06-10 17:27:06.369913

"""

# revision identifiers, used by Alembic.
revision = '114df3b64e8'
down_revision = '47df965c128'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quote_ibfk_1', table_name='quote', type_='foreignkey')
    op.drop_index('customer_id', table_name='quote')
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('customer_id', 'quote', ['customer_id'], unique=True)
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

