"""Add auto_withdraw parameters for customer

Revision ID: 161a1f61b9f
Revises: 42c70f4f379
Create Date: 2015-08-26 18:31:09.591487

"""

# revision identifiers, used by Alembic.
revision = '161a1f61b9f'
down_revision = '42c70f4f379'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('auto_withdraw_amount', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('auto_withdraw_balance_limit', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('auto_withdraw_enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'auto_withdraw_enabled')
    op.drop_column('customer', 'auto_withdraw_balance_limit')
    op.drop_column('customer', 'auto_withdraw_amount')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

