"""Add PromoCode table

Revision ID: 1751dd2a255
Revises: 161a1f61b9f
Create Date: 2015-08-31 15:48:54.297727

"""

# revision identifiers, used by Alembic.
revision = '1751dd2a255'
down_revision = '161a1f61b9f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('promocode_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('promocode_id')
    )
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_code')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

