"""Added customer history

Revision ID: 1802db98d8a
Revises: 917db00580
Create Date: 2015-06-09 14:30:09.471745

"""

# revision identifiers, used by Alembic.
revision = '1802db98d8a'
down_revision = '917db00580'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_history',
    sa.Column('customer_history_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='set null'),
    sa.PrimaryKeyConstraint('customer_history_id')
    )
    op.create_index(op.f('ix_customer_history_customer_id'), 'customer_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_history_date'), 'customer_history', ['date'], unique=False)
    op.add_column('deferred', sa.Column('comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deferred', 'comment')
    op.drop_index(op.f('ix_customer_history_date'), table_name='customer_history')
    op.drop_index(op.f('ix_customer_history_customer_id'), table_name='customer_history')
    op.drop_table('customer_history')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

