"""Added email_confirmed

Revision ID: 1d6f96d1df
Revises: 53244090158
Create Date: 2015-05-25 20:39:10.308414

"""

# revision identifiers, used by Alembic.
revision = '1d6f96d1df'
down_revision = '53244090158'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'email_confirmed')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

