"""changed Option table

Revision ID: 1e05d3e1d36
Revises: 22a50be631f
Create Date: 2015-08-06 13:05:50.982416

"""

# revision identifiers, used by Alembic.
revision = '1e05d3e1d36'
down_revision = '22a50be631f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('key', sa.String(length=32), nullable=False))
    op.add_column('option', sa.Column('value', sa.String(length=32), nullable=True))
    op.drop_column('option', 'last_check')
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('last_check', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('option', 'value')
    op.drop_column('option', 'key')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

