"""Added service table for checking db health

Revision ID: 1e1202c6298
Revises: 5aa5377a1b3
Create Date: 2015-08-05 00:17:51.980623

"""

# revision identifiers, used by Alembic.
revision = '1e1202c6298'
down_revision = '5aa5377a1b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('last_check', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('last_check')
    )
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

