"""Change balance_limit to decimal

Revision ID: 22a50be631f
Revises: 1e1202c6298
Create Date: 2015-08-06 11:08:04.500480

"""

# revision identifiers, used by Alembic.
revision = '22a50be631f'
down_revision = '1e1202c6298'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'balance_limit',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.DECIMAL(precision=28, scale=20),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'balance_limit',
               existing_type=sa.DECIMAL(precision=28, scale=20),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

