"""Added user table

Revision ID: 2b5cc9d88fa
Revises: d01849100f
Create Date: 2015-04-28 14:56:15.455257

"""

# revision identifiers, used by Alembic.
revision = '2b5cc9d88fa'
down_revision = 'd01849100f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table
from sqlalchemy import String, DateTime, Integer, Column


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###
    import conf
    user_table = table('user',
                       Column('user_id', Integer, primary_key=True),
                       Column('email', String),
                       Column('password', String),
                       Column('role', String),
                       Column('name', String),
                       Column('deleted', DateTime),
                       Column('created', DateTime))
    from model.account.user import User

    users = list(conf.user.default_users)
    for u in users:
        u["password"] = User.password_hashing(u["password"])
    op.bulk_insert(user_table, users)


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

