"""Added os_username

Revision ID: 2baf554c632
Revises: 2f658fe6e93
Create Date: 2015-07-29 13:09:02.855283

"""

# revision identifiers, used by Alembic.
revision = '2baf554c632'
down_revision = '2f658fe6e93'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('os_username', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'os_username')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

