"""Added tariff in customer

Revision ID: 2c7b4a4d337
Revises: 4c1fcc9a81d
Create Date: 2015-05-28 16:36:29.151622

"""

# revision identifiers, used by Alembic.
revision = '2c7b4a4d337'
down_revision = '4c1fcc9a81d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_tariff_id'), 'customer', ['tariff_id'], unique=False)
    op.create_foreign_key(None, 'customer', 'tariff', ['tariff_id'], ['tariff_id'])
    op.add_column('tariff', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tariff_default'), 'tariff', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_default'), table_name='tariff')
    op.drop_column('tariff', 'default')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_index(op.f('ix_customer_tariff_id'), table_name='customer')
    op.drop_column('customer', 'tariff_id')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

