"""Add CustomerCard Model

Revision ID: 3096003c162
Revises: 424ed97e693
Create Date: 2015-08-21 00:01:23.876939

"""

# revision identifiers, used by Alembic.
revision = '3096003c162'
down_revision = '424ed97e693'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_card',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('card_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_card')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

