"""Add Flavor table

Revision ID: 31e2d9544da
Revises: 3990fca9b74
Create Date: 2015-11-03 01:33:34.888789

"""

# revision identifiers, used by Alembic.
revision = '31e2d9544da'
down_revision = '32879c33fd7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavor',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('flavor_id', sa.String(length=32), nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('disk', sa.Integer(), nullable=True),
    sa.Column('network', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('flavor_id')
    )
    op.add_column('service', sa.Column('category_id', sa.Enum('custom', 'vm'), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'category_id')
    op.drop_table('flavor')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

