"""Add OpenStack tenant_id and user_id for Customer

Revision ID: 32f11aca04d
Revises: 3fbc589c36d
Create Date: 2015-07-02 14:07:01.117426

"""

# revision identifiers, used by Alembic.
revision = '32f11aca04d'
down_revision = '3fbc589c36d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('os_tenant_id', sa.String(length=32), nullable=False))
    op.add_column('customer', sa.Column('os_user_id', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'os_user_id')
    op.drop_column('customer', 'os_tenant_id')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

