"""added cascade deleting of child tariff

Revision ID: 330979ad5da
Revises: 524a95b3670
Create Date: 2015-09-09 23:52:38.319549

"""

# revision identifiers, used by Alembic.
revision = '330979ad5da'
down_revision = '524a95b3670'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tariff_ibfk_1', 'tariff', type_='foreignkey')
    op.create_foreign_key(None, 'tariff', 'tariff', ['parent_id'], ['tariff_id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariff', type_='foreignkey')
    op.create_foreign_key('tariff_ibfk_1', 'tariff', 'tariff', ['parent_id'], ['tariff_id'])
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

