"""Add column os_dashboard for Customer

Revision ID: 3990fca9b74
Revises: 330979ad5da
Create Date: 2015-10-07 10:20:53.441827

"""

# revision identifiers, used by Alembic.
revision = '3990fca9b74'
down_revision = '330979ad5da'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('os_dashboard', sa.Enum('horizon', 'skyline', 'both'), nullable=False))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'os_dashboard')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

