"""Change decimal precession

Revision ID: 3b666d2ce67
Revises: 4aa3f116140
Create Date: 2015-07-08 13:31:11.358064

"""

# revision identifiers, used by Alembic.
revision = '3b666d2ce67'
down_revision = '4aa3f116140'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'balance',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               type_=sa.DECIMAL(precision=28, scale=20),
               existing_nullable=True)
    op.alter_column('account', 'withdraw',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               type_=sa.DECIMAL(precision=28, scale=20),
               existing_nullable=True)
    op.alter_column('account_history', 'delta',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               type_=sa.DECIMAL(precision=28, scale=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'customer', 'tenant', ['os_tenant_id'], ['tenant_id'])
    op.alter_column('service_price', 'price',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               type_=sa.DECIMAL(precision=28, scale=20),
               existing_nullable=True)
    op.alter_column('service_usage', 'cost',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               type_=sa.DECIMAL(precision=28, scale=20),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_usage', 'cost',
               existing_type=sa.DECIMAL(precision=28, scale=20),
               type_=mysql.DECIMAL(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('service_price', 'price',
               existing_type=sa.DECIMAL(precision=28, scale=20),
               type_=mysql.DECIMAL(precision=20, scale=6),
               existing_nullable=True)
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.alter_column('account_history', 'delta',
               existing_type=sa.DECIMAL(precision=28, scale=20),
               type_=mysql.DECIMAL(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('account', 'withdraw',
               existing_type=sa.DECIMAL(precision=28, scale=20),
               type_=mysql.DECIMAL(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('account', 'balance',
               existing_type=sa.DECIMAL(precision=28, scale=20),
               type_=mysql.DECIMAL(precision=20, scale=6),
               existing_nullable=True)
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

