"""Add customer_type enum property to customer table

Revision ID: 3b8cf0c138b
Revises: 4c81f6e13b5
Create Date: 2015-07-17 03:54:20.096783

"""

# revision identifiers, used by Alembic.
revision = '3b8cf0c138b'
down_revision = '4c81f6e13b5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_type', sa.Enum('private', 'entity'), nullable=False))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'customer_type')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

