"""Add column currency for service_usage

Revision ID: 3cc3881f524
Revises: 5aa5377a1b3
Create Date: 2015-08-05 10:14:27.707859

"""

# revision identifiers, used by Alembic.
revision = '3cc3881f524'
down_revision = '5aa5377a1b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_usage', sa.Column('currency', sa.String(length=3), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_usage', 'currency')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

