"""Added block field in customer table

Revision ID: 3e19c50e864
Revises: 2c0875bb8b6
Create Date: 2015-06-04 22:31:30.169799

"""

# revision identifiers, used by Alembic.
revision = '3e19c50e864'
down_revision = '2c0875bb8b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('blocked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'blocked')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

