"""increase subject field size

Revision ID: 3fbc589c36d
Revises: 37b9ec06ce4
Create Date: 2015-06-24 15:03:25.808096

"""

# revision identifiers, used by Alembic.
revision = '3fbc589c36d'
down_revision = '37b9ec06ce4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'subject',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=78),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'subject',
               existing_type=sa.String(length=78),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

