"""adds need_changing field to ServicePrice model

Revision ID: 41b6fb3ddef
Revises: 31e2d9544da
Create Date: 2015-11-19 22:59:02.557003

"""

# revision identifiers, used by Alembic.
revision = '41b6fb3ddef'
down_revision = '31e2d9544da'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_fitter():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_fitter():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_price', sa.Column('need_changing', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_price', 'need_changing')
    ### end Alembic commands ###

