"""Remove unused tables

Revision ID: 46597280a7c
Revises: 25f9a557214
Create Date: 2015-07-03 17:04:54.413092

"""

# revision identifiers, used by Alembic.
revision = '46597280a7c'
down_revision = '25f9a557214'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order')
    op.drop_table('billing_rate')
    op.drop_constraint('service_usage_ibfk_1', 'service_usage', type_='foreignkey')
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('service_usage_ibfk_1', 'service_usage', 'tenant', ['tenant_id'], ['tenant_id'])
    op.create_table('billing_rate',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('rate', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('sales_order',
    sa.Column('sale_order_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tenant_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start', mysql.DATETIME(), nullable=False),
    sa.Column('end', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name='sales_order_ibfk_1'),
    sa.PrimaryKeyConstraint('sale_order_id', 'tenant_id', 'start', 'end'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

