"""update service_usage and tenant tables

Revision ID: 4aa3f116140
Revises: 46597280a7c
Create Date: 2015-07-07 18:05:33.642330

"""

# revision identifiers, used by Alembic.
revision = '4aa3f116140'
down_revision = '46597280a7c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_usage', 'cost',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=20, scale=6),
               existing_nullable=True)
    op.add_column('tenant', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.alter_column('tenant', 'tenant_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_column('tenant', 'info')
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('info', mysql.TEXT(), nullable=True))
    op.alter_column('tenant', 'tenant_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('tenant', 'deleted')
    op.alter_column('service_usage', 'cost',
               existing_type=sa.DECIMAL(precision=20, scale=6),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=True)
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

