"""set default withdraw_period values to 'month'

Revision ID: 4ac0506251e
Revises: 5943242c5f9
Create Date: 2015-06-18 18:09:42.428620

"""

# revision identifiers, used by Alembic.
revision = '4ac0506251e'
down_revision = '5943242c5f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE customer SET customer.withdraw_period = 'month' WHERE customer.withdraw_period is NULL")
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

