"""added test_period field

Revision ID: 4cfbc4e6089
Revises: 421f9c2bc2d
Create Date: 2015-06-16 14:02:45.285146

"""

# revision identifiers, used by Alembic.
revision = '4cfbc4e6089'
down_revision = '421f9c2bc2d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('test_period', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'test_period')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

