"""Add Payment TransactionId for AccountHistory

Revision ID: 524a95b3670
Revises: 21cc8f612d2
Create Date: 2015-09-04 13:34:37.374812

"""

# revision identifiers, used by Alembic.
revision = '524a95b3670'
down_revision = '21cc8f612d2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_history', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_account_history_transaction_id'), 'account_history', ['transaction_id'], unique=False)
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_history_transaction_id'), table_name='account_history')
    op.drop_column('account_history', 'transaction_id')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

