"""Added Customer

Revision ID: 53244090158
Revises: 2b5cc9d88fa
Create Date: 2015-05-19 15:45:16.314054

"""

# revision identifiers, used by Alembic.
revision = '53244090158'
down_revision = '2b5cc9d88fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=254), nullable=False),
    sa.Column('telephone', sa.String(length=16), nullable=False),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

