"""added withdraw_period column

Revision ID: 5943242c5f9
Revises: b632cd3456
Create Date: 2015-06-18 14:17:45.980457

"""

# revision identifiers, used by Alembic.
revision = '5943242c5f9'
down_revision = 'b632cd3456'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('withdraw_period', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'withdraw_period')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

