"""added 'limit' field for balance limit

Revision ID: 598eddeda2a
Revises: 4ac0506251e
Create Date: 2015-06-23 15:13:55.400557

"""

# revision identifiers, used by Alembic.
revision = '598eddeda2a'
down_revision = '4ac0506251e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('limit', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'limit')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

