"""Add OpenStack user's password (os_user_password) column to customer table

Revision ID: 5cb333dc30
Revises: 3b666d2ce67
Create Date: 2015-07-09 18:20:58.813340

"""

# revision identifiers, used by Alembic.
revision = '5cb333dc30'
down_revision = '3b666d2ce67'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('os_user_password', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'os_user_password')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

