"""change name of 'limit' field

Revision ID: 5ef06a3e19
Revises: 598eddeda2a
Create Date: 2015-06-23 17:09:01.347456

"""

# revision identifiers, used by Alembic.
revision = '5ef06a3e19'
down_revision = '598eddeda2a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('balance_limit', sa.Integer(), nullable=True))
    op.drop_column('customer', 'limit')
    op.execute("UPDATE customer SET customer.balance_limit = 0 WHERE customer.balance_limit is NULL")
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('customer', 'balance_limit')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

