"""Added quote

Revision ID: 917db00580
Revises: 18632a2d5fc
Create Date: 2015-06-05 19:50:27.642760

"""

# revision identifiers, used by Alembic.
revision = '917db00580'
down_revision = '18632a2d5fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('maxImageMeta', sa.Integer(), nullable=True),
    sa.Column('maxPersonality', sa.Integer(), nullable=True),
    sa.Column('maxPersonalitySize', sa.Integer(), nullable=True),
    sa.Column('maxSecurityGroupRules', sa.Integer(), nullable=True),
    sa.Column('maxSecurityGroups', sa.Integer(), nullable=True),
    sa.Column('maxServerMeta', sa.Integer(), nullable=True),
    sa.Column('maxTotalCores', sa.Integer(), nullable=True),
    sa.Column('maxTotalFloatingIps', sa.Integer(), nullable=True),
    sa.Column('maxTotalInstances', sa.Integer(), nullable=True),
    sa.Column('maxTotalKeypairs', sa.Integer(), nullable=True),
    sa.Column('maxTotalRAMSize', sa.Integer(), nullable=True),
    sa.Column('maxServerGroups', sa.Integer(), nullable=True),
    sa.Column('maxServerGroupMembers', sa.Integer(), nullable=True),
    sa.Column('maxTotalVolumeGigabytes', sa.Integer(), nullable=True),
    sa.Column('maxTotalSnapshots', sa.Integer(), nullable=True),
    sa.Column('maxTotalVolumes', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('quote_id'),
    sa.UniqueConstraint('customer_id')
    )
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

