"""First migration

Revision ID: d01849100f
Revises:
Create Date: 2015-04-20 16:20:22.896053

"""

# revision identifiers, used by Alembic.
revision = 'd01849100f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_fitter():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_fitter():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(length=24), nullable=True),
    sa.Column('region', sa.String(length=24), nullable=True),
    sa.Column('availability_zone', sa.String(length=24), nullable=True),
    sa.Column('hour', sa.String(length=8), nullable=True),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('tariff_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('used', sa.Numeric(), nullable=True),
    sa.Column('total_price', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing')
    ### end Alembic commands ###

