"""update tariff history contraint

Revision ID: ec00fe423c
Revises: 41f0af997d7
Create Date: 2015-11-06 16:48:33.054738

"""

# revision identifiers, used by Alembic.
revision = 'ec00fe423c'
down_revision = '41f0af997d7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tariff_history_ibfk_3', 'tariff_history', type_='foreignkey')
    op.create_foreign_key(None, 'tariff_history', 'user', ['user_id'], ['user_id'], ondelete='set null')
    ### end Alembic commands ###


def downgrade_account():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariff_history', type_='foreignkey')
    op.create_foreign_key('tariff_history_ibfk_3', 'tariff_history', 'user', ['user_id'], ['user_id'])
    ### end Alembic commands ###


def upgrade_fitter():
    pass


def downgrade_fitter():
    pass

